package dev

import (
	"errors"

	"github.com/hashicorp-forge/nomad-pipeline/internal/controller/server/state"
	sharedstate "github.com/hashicorp-forge/nomad-pipeline/internal/pkg/state"
)

func (s *State) Runs() state.Runs {
	return &Runs{s: s}
}

type Runs struct {
	s *State
}

func (r *Runs) Create(req *state.RunsCreateReq) (*state.RunsCreateResp, *state.ErrorResp) {
	r.s.runsLock.Lock()
	defer r.s.runsLock.Unlock()

	k := runCompositeKey{id: req.Run.ID, namesapce: req.Run.Namespace}

	_, ok := r.s.runs[k]
	if ok {
		return nil, state.NewErrorResp(errors.New("run already exists"), 409)
	}

	r.s.runs[k] = req.Run
	return &state.RunsCreateResp{}, nil
}

func (r *Runs) Delete(req *state.RunsDeleteReq) (*state.RunsDeleteResp, *state.ErrorResp) {
	r.s.runsLock.Lock()
	defer r.s.runsLock.Unlock()

	k := runCompositeKey{id: req.ID, namesapce: req.Namespace}

	if _, ok := r.s.runs[k]; !ok {
		return nil, state.NewErrorResp(errors.New("run not found"), 404)
	}

	delete(r.s.runs, k)
	return &state.RunsDeleteResp{}, nil
}

func (r *Runs) Get(req *state.RunsGetReq) (*state.RunsGetResp, *state.ErrorResp) {
	r.s.runsLock.RLock()
	defer r.s.runsLock.RUnlock()

	if run, ok := r.s.runs[runCompositeKey{id: req.ID, namesapce: req.Namespace}]; !ok {
		return nil, state.NewErrorResp(errors.New("run not found"), 404)
	} else {
		return &state.RunsGetResp{Run: run.Copy()}, nil
	}
}

func (r *Runs) List(req *state.RunsListReq) (*state.RunsListResp, *state.ErrorResp) {
	r.s.flowsLock.RLock()
	defer r.s.flowsLock.RUnlock()

	var runs []*sharedstate.RunStub

	for _, run := range r.s.runs {

		if req.Namespace == "*" || run.Namespace == req.Namespace {
			runs = append(runs, run.Copy().Stub())
		}
	}

	return &state.RunsListResp{Runs: runs}, nil
}

func (r *Runs) Update(req *state.RunsUpdateReq) (*state.RunsUpdateResp, *state.ErrorResp) {
	r.s.flowsLock.Lock()
	defer r.s.flowsLock.Unlock()

	k := runCompositeKey{id: req.Run.ID, namesapce: req.Run.Namespace}

	// Preserve the original create time, variables, and trigger if the run
	// already exists which are generated by the controller.
	if stateRun, ok := r.s.runs[k]; ok {
		req.Run.Variables = stateRun.Variables
		req.Run.CreateTime = stateRun.CreateTime
		req.Run.Trigger = stateRun.Trigger
	}

	r.s.runs[k] = req.Run
	return &state.RunsUpdateResp{}, nil
}
